### ISSUE TITLE
Issue with view after delete command. 

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#57] opened 2016-10-15 16:03 UTC
![image](https://cloud.githubusercontent.com/assets/16850418/19411413/c7885f88-9333-11e6-8ebe-a0d380818614.png)

I think our view had to be bigger to cater for more than 1 line of output.

**Comment by irvinlim** [comment] 2016-10-15 16:06
The problem is actually the number of items on the screen. Trivial fix, will fix later.

**Comment by irvinlim** [comment] 2016-10-15 18:46
Fixed with e0566a8.

**Closed as completed by irvinlim** 2016-10-15 18:46 UTC
Labels: type.bug
